### ISSUE TITLE
File missing : image Split folder when using CLIP4CIR

### ISSUE THREAD

**Issue by complete-dope** [clic-lab/nlvr#10]
CLIP4CIR is trained on the cirr dataset which is now nlvr2 and it requires something called image_splits. Could you please clarify how it works ? 

https://github.com/ABaldrati/CLIP4Cir#data-preparation

**Comment by alsuhr-c** [comment]
We don't maintain CLIP4CIR or the cirr dataset so we can't answer these questions. Perhaps reach out to those who maintain these projects.
