### ISSUE TITLE
Typos in the dataset

### ISSUE THREAD

**Issue by laituan245** [clic-lab/nlvr#3]
I found that there are many typos in the dataset (e.g., ciircles, yelllow, yelloe, ...). I can send out a small PR that fixes some of the sentences with typos. But I was wondering whether you just want to keep the dataset the same as it is now (i.g., just leave the typos as they are) ?

Thanks for creating this cool dataset.

**Comment by alsuhr-c** [comment]
The typos present are included in the original sentences written by the workers, and will be kept as they are.

You are welcome to include a preprocessing step in your architecture which normalizes textual errors like this, and we will run it when/if you submit the code for evaluation. You could also release such a script for other developers to use if they wish.
