### ISSUE TITLE
question about Implementation details of Image Features+RNN

### ISSUE THREAD

**Issue by ZhuYunzong** [clic-lab/nlvr#4]
In image features + RNN method, you use color, shape and size etc. to construct a set of feature for  every object index. Let's take color and shape into account for example. Given a image with two objects:
Object 1 is represented as： color[0,0,1] shape [1,0,0]
Object 2 is represented as :  color [0,1,0] shape[0,1,0]

You said  you use the concatenation of the one-hot image features to compute the image embeddings
with two layers of size 32.

Does it mean that  you first concatenate the features of a Object, namely Object 1 ->[0,0,1,1,0,0]  and Object 2 ->[0,1,0,0,1,0]. And then they will be  put into Embedding Layer1 to produce vector e1 and e2.
e1 and e2 will be  concatenated again and then put into Embedding Layer2 to produce final image Embedding?

Or it means concatenates all features of all Objects,namely image->[0,0,1,1,0,0,0,1,0,0,1,0] and then it will be embedded by two Embedding Layers?

Maybe both of my comprehensions are wrong. 

Thanks you for this cool corpus.

**Comment by alsuhr-c** [comment]
I believe that we did the second thing: concatenate the one-hot representations of the objects, then put through some fully connected layers with biases (code: https://github.com/alsuhr-c/nlvr-baselines/blob/master/img_ft_rnn.py#L150). Also, note that we padded the boxes with zero-vectors for objects the box did not have (up to 8 objects). It would be a good idea to embed each item individually, which we did not report results on. 

We did try a model where we embedded objects independently with the same embedding matrix, and averaged them, then averaged the embeddings of each box (I'm not sure on the details of this model). This was done to model the order independence of the objects and of the boxes. The performance for this model was roughly the same as the image features + RNN model that we reported, but I don't have exact numbers at the moment.
