### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by kgryte** [clic-lab/nlvr#6]
Would you be able to license the repository data and code? For the data, I might suggest the possible combination of ODbL (https://opendatacommons.org/licenses/odbl/1-0/; for the database) and CC0-1.0 (https://creativecommons.org/publicdomain/zero/1.0/; for the individual images).

**Comment by alsuhr-c** [comment]
Following Microsoft COCO (http://cocodataset.org/#termsofuse), we have licensed the dataset (images, structured representations, and annotations) under CC-BY-4.0 (https://creativecommons.org/licenses/by/4.0/). If there are issues with this, please let us know. 

Clarification May 8, 2021: This license does not apply to the NLVR2 images.
